spring:
  application:
    name: bot2gis
  liquibase:
    enabled: off
    changeLog: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    url: ${POSTGRES_URL}
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
  docker:
    compose:
      enabled: off
server:
  port: ${PORT:8080}

